baseURL: https://lordvidex.live
languageCode: 'en-us'
title: Evans Owamoyo
theme: PaperMod
paginate: 10

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
disqusShortname: lordvidex

googleAnalytics: G-96RFRJ202J

minify:
  disableXML: true

assets:
  favicon: /favicon.ico
  # gold 
  theme_color: '#FFD700'

params:
  title: Evans Owamoyo
  description: >
    Personal Blog of Evans Owamoyo.
    Here, I write articles, share insights and log my notes and thoughts.
  author: 'Evans Owamoyo'
  keywords: [Evans, Owamoyo, Blog, Archives, Logs, lordvidex]
  images: [avatar.jpg, "Evans Owamoyo", "https://lordvidex.live/"]

  env: production
  ShowReadingTime: true
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowToc: true
  comments: true
  defaultTheme: dark
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

  mainSections: ['posts', 'notes']
  
  homeInfoParams:
    Title: Evans Owamoyo
    Content: >
      **Software Engineer** ■ Flutterist ■ Gopher ■ Java developer.
    imageUrl: /avatar.jpg
    imageHeight: 200
    imageWidth: 200
  socialIcons:
    - name: twitter
      url: https://twitter.com/lordvidex
    - name: stackoverflow
      url: https://stackoverflow.com/users/11320345/lordvidex
    - name: github
      url: https://github.com/lordvidex/

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20    
    - identifier: search
      name: Search
      url: /search/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON 